apiVersion: v1
kind: Service
metadata:
  name: firstapp-service
spec:
  type: NodePort
  selector:
    app: firstapp
  ports:
    - protocol: TCP
      port: 80
      targetPort: 5000
      nodePort: 30007  # Puedes especificar un puerto dentro del rango 30000-32767 o dejar que Kubernetes asigne uno automáticamente
